# Generated by Django 4.1.3 on 2025-01-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Words')),
                ('description', models.TextField()),
                ('user_id', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('know', models.BooleanField(blank=True, default=False, null=True, verbose_name='Know')),
            ],
        ),
        migrations.CreateModel(
            name='Tick8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('current_stage', models.PositiveSmallIntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Stage 4'), (5, 'Stage 5'), (6, 'Stage 6'), (7, 'Stage 7'), (8, 'Stage 8')], default=1)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('remmembered', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick8', to='group6.words')),
            ],
        ),
        migrations.CreateModel(
            name='LeitnerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('box_number', models.PositiveSmallIntegerField(choices=[(1, 'Box 1'), (2, 'Box 2'), (3, 'Box 3'), (4, 'Box 4'), (5, 'Box 5')], default=1)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leitner', to='group6.words')),
            ],
        ),
    ]
